from typing import List, Dict, Any

SERVICE_CATEGORIES = [
    {
        "id": "sites_apps",
        "name": "Situs dan aplikasi",
        "title": "Situs dan aplikasi",
        "description": "Aplikasi web dan beranda yang diakses melalui browser.",
    },
    {
        "id": "operations",
        "name": "Operasional",
        "title": "Operasional",
        "description": "Panel pemantauan, manajemen layanan, dan brankas kredensial.",
    },
    {
        "id": "integrations_api",
        "name": "Integrasi dan API",
        "title": "Integrasi dan API",
        "description": "Endpoint sinkronisasi dan gateway layanan antar-mesin.",
    },
]

CANONICAL_SERVICES: List[Dict[str, Any]] = [
    {
        "id": "digitalneeds",
        "name": "DigitalNeeds",
        "url": "https://digitalneeds.my.id",
        "domain": "digitalneeds.my.id",
        "hostname": "digitalneeds.my.id",
        "category": "Situs dan aplikasi",
        "category_id": "sites_apps",
        "access_type": "web",
        "access_label": "Halaman publik",
        "role": "Gateway beranda utama ekosistem digitalneeds.my.id.",
        "description": "Gateway beranda utama ekosistem digitalneeds.my.id.",
        "is_quick_link": True,
        "is_current": False,
    },
    {
        "id": "graduance",
        "name": "Graduance",
        "url": "https://graduance.digitalneeds.my.id",
        "domain": "graduance.digitalneeds.my.id",
        "hostname": "graduance.digitalneeds.my.id",
        "category": "Situs dan aplikasi",
        "category_id": "sites_apps",
        "access_type": "web",
        "access_label": "Aplikasi web",
        "role": "Portal informasi bimbingan skripsi dan tugas akhir akademik.",
        "description": "Portal informasi bimbingan skripsi dan tugas akhir akademik.",
        "is_quick_link": True,
        "is_current": False,
    },
    {
        "id": "cv-builder",
        "name": "CV Builder",
        "url": "https://cv.digitalneeds.my.id",
        "domain": "cv.digitalneeds.my.id",
        "hostname": "cv.digitalneeds.my.id",
        "category": "Situs dan aplikasi",
        "category_id": "sites_apps",
        "access_type": "web",
        "access_label": "Aplikasi web",
        "role": "Aplikasi penyusun CV standar ATS bahasa Indonesia dan Inggris.",
        "description": "Aplikasi penyusun CV standar ATS bahasa Indonesia dan Inggris.",
        "is_quick_link": False,
        "is_current": False,
    },
    {
        "id": "uptime-kuma",
        "name": "Uptime Kuma",
        "url": "https://status.digitalneeds.my.id",
        "domain": "status.digitalneeds.my.id",
        "hostname": "status.digitalneeds.my.id",
        "category": "Operasional",
        "category_id": "operations",
        "access_type": "web",
        "access_label": "Halaman status publik",
        "role": "Halaman status ketersediaan layanan publik dan riwayat uptime.",
        "description": "Halaman status ketersediaan layanan publik dan riwayat uptime.",
        "secondary_url": "https://status.digitalneeds.my.id/dashboard",
        "secondary_label": "Admin Kuma (/dashboard)",
        "is_quick_link": True,
        "is_current": False,
    },
    {
        "id": "dashboard",
        "name": "VPS Monitor Dashboard",
        "url": "https://dashboard.digitalneeds.my.id",
        "domain": "dashboard.digitalneeds.my.id",
        "hostname": "dashboard.digitalneeds.my.id",
        "category": "Operasional",
        "category_id": "operations",
        "access_type": "admin",
        "access_label": "Halaman aktif (PIN)",
        "role": "Mission Control privat untuk metrik host, Docker, log, dan backup.",
        "description": "Mission Control privat untuk metrik host, Docker, log, dan backup.",
        "is_quick_link": False,
        "is_current": True,
    },
    {
        "id": "9router",
        "name": "9Router",
        "url": "https://router.digitalneeds.my.id",
        "domain": "router.digitalneeds.my.id",
        "hostname": "router.digitalneeds.my.id",
        "category": "Operasional",
        "category_id": "operations",
        "access_type": "admin",
        "access_label": "Dashboard layanan (Login)",
        "role": "Gateway model AI terpusat dan penghemat token (mengarahkan ke /dashboard).",
        "description": "Gateway model AI terpusat dan penghemat token (mengarahkan ke /dashboard).",
        "is_quick_link": False,
        "is_current": False,
    },
    {
        "id": "vaultwarden",
        "name": "Vaultwarden",
        "url": "https://vault.digitalneeds.my.id",
        "domain": "vault.digitalneeds.my.id",
        "hostname": "vault.digitalneeds.my.id",
        "category": "Integrasi dan API",
        "category_id": "integrations_api",
        "access_type": "admin",
        "access_label": "Brankas sandi (Login)",
        "role": "Pengelola kata sandi mandiri terenkripsi ujung-ke-ujung (E2EE).",
        "description": "Pengelola kata sandi mandiri terenkripsi ujung-ke-ujung (E2EE).",
        "is_quick_link": False,
        "is_current": False,
    },
    {
        "id": "obsidian-sync",
        "name": "Obsidian Sync",
        "url": "https://sync.digitalneeds.my.id",
        "domain": "sync.digitalneeds.my.id",
        "hostname": "sync.digitalneeds.my.id",
        "category": "Integrasi dan API",
        "category_id": "integrations_api",
        "access_type": "api",
        "access_label": "Endpoint sinkronisasi (401 Auth)",
        "role": "Server CouchDB LiveSync untuk replikasi catatan antar-perangkat (bukan UI web).",
        "description": "Server CouchDB LiveSync untuk replikasi catatan antar-perangkat (bukan UI web).",
        "is_quick_link": False,
        "is_current": False,
    },
    {
        "id": "brain-gateway",
        "name": "Second Brain Gateway",
        "url": "https://brain.digitalneeds.my.id",
        "domain": "brain.digitalneeds.my.id",
        "hostname": "brain.digitalneeds.my.id",
        "category": "Integrasi dan API",
        "category_id": "integrations_api",
        "access_type": "api",
        "access_label": "Gateway API (Bearer Auth)",
        "role": "Layanan API baca-saja tersanitasi untuk akses pengetahuan Second Brain.",
        "description": "Layanan API baca-saja tersanitasi untuk akses pengetahuan Second Brain.",
        "is_quick_link": False,
        "is_current": False,
    },
]


def get_service_catalog() -> Dict[str, Any]:
    """Return the canonical 9-domain catalog, quick links, and grouped categories."""
    quick_links = [s for s in CANONICAL_SERVICES if s.get("is_quick_link")]
    categories = []
    for cat in SERVICE_CATEGORIES:
        items = [s for s in CANONICAL_SERVICES if s["category_id"] == cat["id"]]
        categories.append(
            {
                "id": cat["id"],
                "name": cat["name"],
                "title": cat["title"],
                "description": cat["description"],
                "services": items,
            }
        )

    return {
        "total": len(CANONICAL_SERVICES),
        "total_services": len(CANONICAL_SERVICES),
        "quick_links": quick_links,
        "categories": categories,
        "groups": categories,
        "services": CANONICAL_SERVICES,
    }
